version: '3.7'
services:
  postgres:
    image: 'postgres:13'
    container_name: 'WebStore-postgres'
    environment:
      POSTGRES_PASSWORD: n09071998
      POSTGRES_USER: postgres
      POSTGRES_DB: WebStore
  back:
    build: ./Back
    container_name: WebStore-backend
    ports:
      - 8081:8081

  front:
    build: ./Front
    container_name: WebStore-front
    ports:
      - 8080:8080
